#!/bin/bash
ENV=$1

if [ -z $1 ]; then
	echo "Usage: `basename $0` <environment>"
	exit 1
fi

case ${ENV} in
	"production")
		yarn run build-production
		;;
	"staging")
		yarn run build-staging
		;;
esac
