#!/bin/bash
ENV=$1

if [ -z $1 ]; then
	echo "Usage: `basename $0` <environment>"
	exit 1
fi

function deploy {
    PROJECT=$1

    yarn run deploy -- --project ${PROJECT} --token="$FIREBASE_TOKEN";
}

case ${ENV} in
	"staging")
		scripts/build staging
		deploy navory-dev
		;;
	"production")
		scripts/build production
		deploy project-5028999388129729441
		;;
esac
