#!/bin/bash
ENV=$1

if [ -z $1 ]; then
	echo "Usage: `basename $0` <environment>"
	exit 1
fi

function deploy {
    PROJECT=$1

    npm run build
    firebase deploy --project ${PROJECT} --token="$FIREBASE_TOKEN";

}

case ${ENV} in
	"development")
		deploy navory-dev
		;;
	"production")
		deploy navory
		;;
esac
