name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install and test
      run: |
        yarn install
        yarn test
    - name: Build and deploy staging
      if: github.ref === 'develop'
        yarn build:staging
        yarn deploy:staging
    - name: Build and deploy master
      if: github.ref === 'master'
        yarn build:production
        yarn deploy:production
