name: CI

on: push

jobs:
  build:
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install and test
      run: |
        yarn install
    - name: Build and deploy staging
      run: |
        yarn build:staging
        yarn deploy:staging
      if: github.ref == 'refs/heads/develop'
    - name: Build and deploy master
      run: |
        yarn build:production
        yarn deploy:production
      if: github.ref == 'refs/heads/master'
